# Use a base image with OpenJDK pre-installed
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /demo

# Copy the packaged JAR file into the container
COPY target/my-spring-boot-app.jar /app/app.jar

# Expose the port that your Spring Boot application uses (default is 8080)
EXPOSE 8080

# Command to run your Spring Boot application when the container starts
CMD ["java", "-jar", "app.jar"]
